import { uuid } from './helpers';
import type { User } from '@/types/api';

export const users: User[] = [
  {
    id: uuid(9),
    companyId: null,
    email: 'admin@demo.com',
    lastName: '管理者',
    firstName: '運営',
    role: 'admin',
    phone: '090-0000-0001',
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: uuid(10),
    companyId: uuid(1),
    lineUserId: 'demo-owner',
    email: 'owner@demo.com',
    lastName: '山田',
    firstName: '太郎',
    lastNameKana: 'ヤマダ',
    firstNameKana: 'タロウ',
    role: 'owner',
    phone: '090-1111-2222',
    company: { id: uuid(1), companyName: 'デモ建設株式会社', companyType: 'general_contractor' },
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: uuid(12),
    companyId: uuid(2),
    email: 'suzuki@tokyo-densetsu.co.jp',
    lastName: '鈴木',
    firstName: '一郎',
    lastNameKana: 'スズキ',
    firstNameKana: 'イチロウ',
    role: 'owner',
    phone: '090-3333-4444',
    company: { id: uuid(2), companyName: '東京電設工業株式会社', companyType: 'subcontractor' },
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: uuid(11),
    companyId: uuid(1),
    lineUserId: 'demo-worker',
    email: 'worker@demo.com',
    lastName: '佐藤',
    firstName: '花子',
    lastNameKana: 'サトウ',
    firstNameKana: 'ハナコ',
    role: 'worker',
    phone: '090-2222-3333',
    defaultDailyRate: 18000,
    company: { id: uuid(1), companyName: 'デモ建設株式会社', companyType: 'general_contractor' },
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: uuid(13),
    companyId: uuid(1),
    email: 'tanaka@demo-kensetsu.co.jp',
    lastName: '田中',
    firstName: '健一',
    lastNameKana: 'タナカ',
    firstNameKana: 'ケンイチ',
    role: 'worker',
    phone: '090-4444-5555',
    defaultDailyRate: 22000,
    company: { id: uuid(1), companyName: 'デモ建設株式会社', companyType: 'general_contractor' },
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: uuid(14),
    companyId: uuid(1),
    email: 'takahashi@demo-kensetsu.co.jp',
    lastName: '高橋',
    firstName: '勇気',
    lastNameKana: 'タカハシ',
    firstNameKana: 'ユウキ',
    role: 'worker',
    phone: '090-5555-6666',
    defaultDailyRate: 20000,
    company: { id: uuid(1), companyName: 'デモ建設株式会社', companyType: 'general_contractor' },
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: uuid(15),
    companyId: uuid(2),
    email: 'ito@tokyo-densetsu.co.jp',
    lastName: '伊藤',
    firstName: '大輔',
    lastNameKana: 'イトウ',
    firstNameKana: 'ダイスケ',
    role: 'worker',
    phone: '090-6666-7777',
    defaultDailyRate: 25000,
    company: { id: uuid(2), companyName: '東京電設工業株式会社', companyType: 'subcontractor' },
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: uuid(16),
    companyId: uuid(2),
    email: 'watanabe@tokyo-densetsu.co.jp',
    lastName: '渡辺',
    firstName: '翔太',
    lastNameKana: 'ワタナベ',
    firstNameKana: 'ショウタ',
    role: 'worker',
    phone: '090-7777-8888',
    defaultDailyRate: 19000,
    company: { id: uuid(2), companyName: '東京電設工業株式会社', companyType: 'subcontractor' },
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: uuid(17),
    companyId: uuid(3),
    email: 'kobayashi@kanto-sakan.co.jp',
    lastName: '小林',
    firstName: '正和',
    lastNameKana: 'コバヤシ',
    firstNameKana: 'マサカズ',
    role: 'worker',
    phone: '090-8888-9999',
    defaultDailyRate: 23000,
    company: { id: uuid(3), companyName: '関東左官工業有限会社', companyType: 'subcontractor' },
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: uuid(18),
    companyId: uuid(3),
    email: 'kato@kanto-sakan.co.jp',
    lastName: '加藤',
    firstName: '美咲',
    lastNameKana: 'カトウ',
    firstNameKana: 'ミサキ',
    role: 'worker',
    phone: '090-9999-0000',
    defaultDailyRate: 18000,
    company: { id: uuid(3), companyName: '関東左官工業有限会社', companyType: 'subcontractor' },
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: uuid(19),
    companyId: uuid(1),
    email: 'yoshida@demo-kensetsu.co.jp',
    lastName: '吉田',
    firstName: '隆司',
    lastNameKana: 'ヨシダ',
    firstNameKana: 'タカシ',
    role: 'worker',
    phone: '090-1111-0000',
    defaultDailyRate: 21000,
    company: { id: uuid(1), companyName: 'デモ建設株式会社', companyType: 'general_contractor' },
    createdAt: '2026-01-01T00:00:00.000Z',
  },
];
